### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by wibeasley** [paulponcet/modeest#4]
Hi @polmath, I don't understanding file encoding issues well, and I typically run away from them, or take the path of least resistance.  

In case it helps you to know, it may be difficult for Americans to edit and resubmit existing code.  Characters like the accented 'e' in the file below aren't interpreted correctly with my installations of RStudio, Notepad++, Notepad, or NetBeans.  From what I could tell, the GitHub browser did a better job, so I edited it directly in there.

I'm not saying you should change anything so it's easier for us to work with.  But I wanted to let you know there might be extra friction/obstacles developing.

![image](https://cloud.githubusercontent.com/assets/1372890/4348867/7b672ca2-419f-11e4-9f7b-d340c173a3e9.png)

**Comment by paulponcet** [comment]
Files should now be cleaned up.
