### ISSUE TITLE
Calculating mode on factor

### ISSUE THREAD

**Issue by clemens-zauchner** [paulponcet/modeest#6]
I have found this question on [stackoverflow](https://stackoverflow.com/questions/46845848/statistical-mode-of-a-categorical-variable-in-r-using-mlv/46846474#46846474) .  When trying to calculate the mode from a factor like this:
```
color <- c("blue","green","blue","blue","green","yellow","pink","blue")
color <- as.factor(color)
```
The mode is `NA`:
```
mlv.factor(x=color,method='mfv')

Mode (most frequent value): NA 
Bickel's modal skewness: -2 
Call: mlv.factor(x = color, method = "mfv") 
Warning message:
In discrete(x, ...) : NAs introduced by coercion
```
I have looked into the function an found that `mlv.factor()` calls `discrete()`:
`th <- discrete(x, ...)`

```
f <- factor(x)
f
[1] blue   green  blue   blue   green  yellow pink   blue  
Levels: blue green pink yellow

tf <- tabulate(f)
tf
[1] 4 2 1 1

as.numeric(levels(f)[tf == max(tf)])
[1] NA
Warning message:
NAs introduced by coercion 
```
It cannot coerce `"blue"` to numeric, hence the function does not return anything.

**Comment by clemens-zauchner** [comment]
If you want, I can contribute a simple fix.

**Comment by paulponcet** [comment]
'modeest' now reexports the 'mfv' function from package 'statip' (use 'statip' with version 0.1.5 or later). 
This gives: 

    library(modeest) 
    color <- c("blue","green","blue","blue","green","yellow","pink","blue")
    color <- as.factor(color)
    mlv(color) # "blue"

    # Or equivalently: 
    mfv(color) # "blue"
